### ISSUE TITLE
Axolotl and Astronos cannot move in water

### ISSUE THREAD

**Issue by DaRealPizza** [Latokike/lato-origins#31] opened 2022-04-23 17:39 UTC
So basically the origins axolotl and Astronos cannot move an inch while submerged in water, they can only move up and down. I have not been able to recreate this with any other origins.

We use the mods: Origins, Mob Origins, Lato Origins, Pehkui and Simple Voice chat on minecraft version 1.18.1

I've tried restarting the server a couple times but the issue still continues

**Comment by Ultimushadow** [comment] 2022-04-24 09:35
This issue is definitely with how swim speed is handled. Messing around with the code, I changed the swim speed in the Astronos and changed the "inverted" to true, and I could swim in water just fine
Axolotl has a serious issue as well, specifically the "play_dead" power does not operate as intended. When this power is applied to humans using /power they stop immediately in water, and for some reason I think the play_dead_resource code is bugged? I can't tell, but hopefully you know where to look

**Comment by DaRealPizza** [comment] 2022-04-24 15:58
> This issue is definitely with how swim speed is handled. Messing around with the code, I changed the swim speed in the Astronos and changed the "inverted" to true, and I could swim in water just fine Axolotl has a serious issue as well, specifically the "play_dead" power does not operate as intended. When this power is applied to humans using /power they stop immediately in water, and for some reason I think the play_dead_resource code is bugged? I can't tell, but hopefully you know where to look

So i managed to fix axolotl not working, but im not very good at java and i dont exactly know how to go about fixing Astronos. Could you maybe help me with that or send me your fixed code (assuming you still have it)?

**Comment by xAptly** [comment] 2022-08-01 05:30
Can someone please explain how to fix this? I really need this fixed for a server and this is a huge issue we’re having. I don’t know how to edit the mod and go in and fix both but I’ll do it if someone explains how. Please bro.

**Comment by latokike** [comment] 2022-09-17 09:49
It should be fixed now!

**Closed as completed by latokike** 2022-09-17 09:49 UTC
